import time
def opening(ui,player,partner):
    time.sleep(0.5)
    print("本游戏含有大量成人向色情描写，以及少量精神压力的描写，请自行酌情游玩。\n")
    time.sleep(0.5)
    print("游玩方法：\n")
    time.sleep(0.5)
    print("文字部分 - 在文字暂停播放时按回车键继续\n回合制部分 - 选择一个或多个行动，用空格分隔编号，例如：1 3 5 输入后回车。每个身体部位仅能执行最多一个动作。如当前回合有默认行动，可以不用输入对应编号，默认行动自动执行。\n")
    time.sleep(0.5)
    print("当佐音达到高潮时游戏结束\n\n")
    time.sleep(0.5)
    print("错误的输入可能会导致游戏崩溃\n\n")
    time.sleep(0.5)
    ans = input("（按回车键继续，或输入skip跳过开场文字）")
    if ans == "skip":
        return

    ui.clean_screen()
    ui.typewriter("地下一楼的走廊狭长又昏暗，堆满了杂物。出勤的队员收队时要登记、清理和盘点，这里是他们去往休整区的必经之路。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你在这里等着佐音。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("一阵虚弱感和疼痛袭来，让你站都站不稳。你干脆顺势坐在地板上，用背后的墙壁支撑自己。\n",0.1,'bold red')
    time.sleep(0.1)
    ui.typewriter("有三三两两的队员从你身边经过，但你对他们毫无兴趣，也没有人理睬你。直到某个脚步声响起，这声音你很熟悉。\n", 0.1)
    ui.typewriter("你的头突然变得沉重，让你没办法看向脚步声的主人。\n\n", 0.1, 'reverse')

    time.sleep(0.1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("“阿伦？”\n",0.2)
    input("【抬头】")
    
    ui.clean_screen()
    ui.typewriter("他出声叫你，你绞着双手，暗中用力掐了自己一下，好借着疼痛振作起来，再抬起头，装出一副刚发现他的样子。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("站在你面前的是佐音，他身上的制服满是污渍，那张你日思夜想的脸藏在领子和有点凌乱的头发里。他的大眼睛正穿过发丝目不转睛地盯着你看。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你以为自己还需要再用点力气对他微笑，但没有，喜悦就这么自然而然地在你身体里聚集，然后一路飘到了你的脸上，变成了一个大大的傻笑。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“佐音！”",0.1, line_break=False)
    ui.typewriter("你欢快地大叫他的名字。他把手伸向你，想要拉你起来。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你起身，",0.1,line_break=False)
    ui.typewriter("一阵突发的头晕目眩让你直接扑倒在了他身上，",0.1,'red bold',line_break=False)
    ui.typewriter("他连忙接住你，你顺势紧紧抱住了他。",0.1,line_break=False)
    ui.typewriter("眼前发黑，什么都看不见。",0.1,'red bold',line_break=False)
    ui.typewriter("但隔着制服你能摸到他的身体，光是这样就让你觉得长期以来的空虚感被填满了。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“那个……我身上很脏……”", 0.2, line_break=False)
    ui.typewriter("他没敢回应这个拥抱，双臂滑稽地悬在半空。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他的制服上混着油污、尘土、泥泞、血痕和一些散发着刺鼻气味的干涸液体。不过你并不在乎。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("有其他的队员陆续经过你们。不知是谁冲你们吹了一声口哨。你看也没看一眼。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他们的脚步声走远了。\n",0.1)
    input("【继续】")
    
    ui.clean_screen()
    ui.typewriter("“我想你了。”你说，侧过头去亲吻他的耳朵，“你们这次行动可真久，有三个月了吧。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“嗯。”",0.2,line_break=False)
    ui.typewriter("他小心地把手搭在你的背上，没再多说什么。想必这三个月的外勤并不是很令人愉快。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“今晚别回去了。”你轻声说，“我找到一个房间。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他明白了你的意思，脸一下子红了，但并没有回绝。\n",0.1)
    time.sleep(0.5)
    ui.typewriter("* * *\n",0.2)
    time.sleep(0.5)
    ui.typewriter("你拉着他走到教官宿舍区。这里比你们学徒兵住的大通铺条件好很多，都是单人单间，监控都没安几个。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("在HII的新领导上台以后，不少教官被调离了，这里空出了好几个房间，也没什么人走动。你走到其中一间门前，从身上摸出一个发卡，伸到锁眼里拨弄着。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……”",0.2,line_break=False)
    ui.typewriter("佐音显得有些不安，但没说什么。\n",0.1)
    time.sleep(0.1)
    input("（开锁）")
    ui.typewriter("\n这不是你第一次开这把锁，你轻车熟路地打开了它，走进了房间。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你把佐音拽进来，砰地一声把门关上并反锁。\n")
    input("【继续】")
    
    ui.clean_screen()
    ui.typewriter("你一把将他推到墙上，开始吻他，你顺势扒开他那身脏兮兮的制服，让它滑落到地上。\n你的身体开始发烫，思维逐渐不受控制，你等太久了，现在除了肉体上的抚慰你什么都不想要。\n")
    time.sleep(0.1)
    ui.typewriter("这种无法理智思考的感觉太讨厌了，你感觉自己像条发情的狗。\n但，这种想法一秒就消失了。\n",0.1,text_style="reverse")
    time.sleep(0.1)
    ui.typewriter("也许是你们太长时间没接触过，佐音显得格外不知所措：",0.1,line_break=False)
    ui.typewriter("“等，等一下，我想……唔……”\n",0.2)
    time.sleep(0.1)
    ui.typewriter("你没等他说完就又用吻堵住了他的嘴。你用手紧紧箍住他的头，舌头粗暴地侵略他的口腔，毫无克制地与他纠缠。")
    ui.typewriter("你其实不确定自己在干什么，只是被积攒了多时的渴望和翻涌的情绪掌控着。\n")
    time.sleep(0.1)
    ui.typewriter("你想念他，你需要他，你不能失去他。\n",0.2,text_style="reverse")
    time.sleep(0.1)
    ui.typewriter("伤感、愤怒和恐惧裹挟着你，你觉得自己快被撕裂了，直到你感受到佐音温柔的回应，他抱紧了你，顺从而配合地被你亲吻撕咬。\n")
    ui.typewriter("他现在就在这里，和你一起。\n",0.2,text_style="reverse")
    ui.typewriter("你感觉自己终于可以放松一点点，松开了佐音。他看着你的眼神有点担忧，但你没给他发话的机会。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“你想洗澡是不是？”你问。他被你的话题带跑，点了点头。",0.1)
    ui.typewriter("“我早想到了。”你捧着他的脸又亲了一下，冲他微笑，“这间屋子我打扫和检查过了，连干净衣服都给你准备了。厕所那个水龙头还能用，不过只有冷水。去吧。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……我洗好就来找你。”",0.2,line_break=False)
    ui.typewriter("佐音纠结了半天，蚊子哼似地说，然后走进了浴室。\n\n",0.1)
    input("【等待】")
    
    ui.clean_screen()
    ui.typewriter("你躺在床上，浴室里的水声让你浮想联翩，你感觉到自己的下体已经支了起来，你想象着他裸体的样子，想象他顺从地在你身下打开身体。\n",0.1,line_break=False)
    ui.typewriter("你的脑子里嗡嗡作响，身体的某处有什么一跳一跳地刺痛着你，不能触碰他的每一秒都在加剧这种疼痛。\n",text_style="red bold")
    time.sleep(0.1)
    ui.typewriter("你等了很久，终于他红着脸来了，轻轻爬上床，在你身边坐下。老旧的床架咯吱了一声。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“躺过来。”你说。他顺从地躺下，望着你，等着你的下一步动作。\n",0.1)
    time.sleep(0.1)
    input("【继续】")

def ending(ui,player,partner):
    ui.clean_screen()
    ui.typewriter("佐音已经到了射精的边缘，他的身体不受控制地抽搐起来，手指在你身上抓出一道道痕迹。")
    ui.typewriter("“阿伦……阿伦……！！”",line_break=False)
    ui.typewriter("他用最缠绵的声音叫着你的名字达到了巅峰。\n")
    time.sleep(0.1)
    if partner.bodyParts['阴茎']['currentAction'] == "blowjob":
        ui.typewriter("精液灌满了你的嘴，他积累的量太多了，你不得不连续吞咽好几次才不会被呛到。\n即使如此，还是有些从你的嘴角漏了出来。\n")
    elif partner.bodyParts['阴茎']['isCovered']:
        ui.typewriter("大片的湿痕出现在他的内裤上，甚至有些精液顺着裤腿流到了他的大腿上。他肯定有很久没有发泄过了。\n")
    else:
        ui.typewriter("乳白色的液体喷溅在床上、你的手上、身上，你有点狼狈地用衣服把自己擦干净。量有点多，他肯定有很久没有发泄过了。\n")
    time.sleep(0.1)
    ui.typewriter("过了许久，他才慢慢恢复了平静，脸上的红晕久久没有散去。\n")
    time.sleep(1)
    ui.typewriter("“我爱你。”",0.2,line_break=False)
    ui.typewriter("他凑到你的耳边轻轻对你说，然后在你脸上亲了一下。你回吻了他，把头倚在他的颈窝。他的皮肤还是滚烫的。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你们就这么依偎了一会，直到佐音把他的气喘匀。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……你还没有到呢，”",0.2,line_break=False)
    ui.typewriter("他看着你依旧硬邦邦的下体，伸出手去触碰它，",0.1,line_break=False)
    ui.typewriter("“我……我来帮帮你。”\n",0.2)
    time.sleep(0.1)
    ui.typewriter("（未完）\n\n",0.1)
