import time
def opening(ui,player,partner):
    ui.clean_screen()
    #ui.typewriter("",0.1)
    ui.typewriter("（前略）\n",0.1)
    time.sleep(0.1)
    ui.typewriter("地下一楼的走廊狭长又昏暗，堆满了杂物。队员收队时要登记、清理和盘点，这里是他们去往休整区的必经之路。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你在这里等着佐音。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你感到一阵虚弱和疼痛，干脆坐在地板上，用背后的墙壁支撑自己。\n",0.1,'bold red')
    time.sleep(0.1)
    ui.typewriter("有三三两两的队员从你身边经过，但你对他们毫无兴趣。直到某个脚步声响起。", 0.1)
    ui.typewriter("你的头突然变得沉重，让你没办法把头转向脚步声的主人。\n\n", 0.1, 'reverse')

    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("哒\n",0.1)
    time.sleep(1)
    ui.typewriter("“阿伦？”\n",0.2,'cyan bold')
    input("【抬头】（按回车键继续）")
    
    ui.clean_screen()
    ui.typewriter("他出声叫你，你绞着双手，暗中用力掐了自己一下，好借着疼痛振作起来，再抬起头，装出一副刚发现他的样子。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他穿着全是污渍的制服夹层，秀气的脸藏在领子和头发里，刘海长得有些长了，但一双大眼睛正穿过发丝目不转睛地盯着你看。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你以为自己还需要用点力气对他微笑，但没有，喜悦就这么自然而然地在你身体里聚集，然后一路飘到了你的脸上，变成了一个傻笑。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“佐音！”",0.1)
    ui.typewriter("你欢快地大叫他的名字。他把手伸向你，想要拉你起来。",0.1)
    time.sleep(0.1)
    ui.typewriter("你起身，",0.1,line_break=False)
    ui.typewriter("一阵突发的头晕目眩让你直接扑在了他身上，",0.1,'red bold',line_break=False)
    ui.typewriter("他接住你，你顺势紧紧抱上去。",0.1,line_break=False)
    ui.typewriter("眼前发黑，什么都看不见。",0.1,'red bold',line_break=False)
    ui.typewriter("但隔着制服你能摸到他的身体，光是这样就让你觉得长期以来的空虚感被填满了。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“那个……我身上很脏……”", 0.2, 'cyan bold',line_break=False)
    ui.typewriter("他没敢回应这个拥抱，双臂可笑地悬在半空。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他的制服上混着油污、尘土、泥泞、血痕和一些散发着刺鼻气味的干涸液体。不过你并不在乎。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("有其他的队员陆续经过你们。不知道是谁冲你们吹了一声口哨。你没搭理他们。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他们的脚步声走远了。\n",0.1)
    input("【继续】")
    
    ui.clean_screen()
    ui.typewriter("“我想你了。”你说，侧过头去亲吻他的耳朵，“你们这次行动可真久，有三个月了吧。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“嗯。”",0.2,"cyan bold",line_break=False)
    ui.typewriter("他轻轻地把手搭在你身上，没再说什么。想必这三个月并不是很令人愉快。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“今晚别回去了。”你说，“我找到一个房间。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("他明白了你的意思，脸一下子红了，但并没有回绝的意思。\n",0.1)
    time.sleep(0.5)
    ui.typewriter("* * *\n",0.1)
    time.sleep(0.5)
    ui.typewriter("你拉着他走到教官宿舍区。这里比你们的大通铺条件好很多，都是单人单间，监控都没安几个。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("在█████以后，这里逐渐被废弃了，只有几个房间还在使用中。你走到其中一间门前，从身上摸出一个发卡，伸到门锁里拨弄着。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……”",0.2,"cyan bold",line_break=False)
    ui.typewriter("佐音显得有些不安，但没说什么。\n",0.1)
    time.sleep(0.1)
    input("（开锁）\n")
    ui.typewriter("这不是你第一次开这把锁，三下两下就又打开了它。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("你把佐音拽进来，砰地一声把门关上并反锁。\n")
    input("【继续】")
    
    ui.clean_screen()
    ui.typewriter("你一把将他推到墙上然后吻他，扒下他的制服，爱抚他的身体。你的身体开始发烫，思维逐渐不受控制，你等太久了，现在除了肉体上的欢愉你什么都不想要。\n")
    time.sleep(0.1)
    ui.typewriter("你讨厌这种无法理智思考的感觉，你感觉自己像条发情的狗。但这种想法一秒就结束了。\n",0.1,text_style="reverse")
    time.sleep(0.1)
    ui.typewriter("也许是你们太长时间没接触过，佐音显得格外拘谨：",0.1,line_break=False)
    ui.typewriter("“等，等一下，我想洗澡……”\n",0.2,"bold cyan")
    time.sleep(0.1)
    ui.typewriter("“就知道你会这么说。”你捧着他的脸又亲了一下，“这间屋子我打扫和检查过了，连干净衣服都给你拿来了，厕所那个水龙头还能用，不过只有冷水。去吧。”\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……我洗好就来找你。”",0.2,"bold cyan",line_break=False)
    ui.typewriter("佐音纠结了半天，蚊子哼似地说，然后走进了浴室。\n",0.1)
    time.sleep(0.5)
    ui.typewriter("* * *\n",0.1)
    time.sleep(0.5)
    ui.typewriter("你躺在床上，浴室里的水声让你浮想联翩，你感觉到自己的下体已经支了起来，你想象着他裸体的样子，想象他顺从地在你身下打开身体。",line_break=False)
    ui.typewriter("你的脑子已经完全无法思考除了和他做爱之外的事情。\n",text_style="red bold")
    time.sleep(0.1)
    ui.typewriter("你等了很久，终于他红着脸来了，轻轻爬上床，在你身边坐下。老旧的床架咯吱了一声。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“我们开始吧？”你问。他点头，顺从地躺下，等着你的动作。",0.1)
    time.sleep(0.1)
    input("【继续】")

def ending(ui,player,partner):
    ui.clean_screen()
    ui.typewriter("佐音已经到了射精的边缘，他的身体不受控制地抽搐起来，手指在你身上抓出一道道痕迹。")
    ui.typewriter("“阿伦……阿伦……啊啊！！”",text_style="bold cyan",line_break=False)
    ui.typewriter("他用最缠绵的声音呻吟着达到了巅峰。乳白色的液体从他的身体涌出。\n")
    time.sleep(0.1)
    if partner.bodyParts['阴茎']['currentAction'] == "blowjob":
        ui.typewriter("精液灌满了你的嘴，他积累的量太多了，你不得不连续吞咽好几次才不会被呛到。\n即使如此，还是有些从你的嘴角漏了出来。\n")
    elif partner.bodyParts['阴茎']['isCovered'] == 'True':
        ui.typewriter("大片的湿痕出现在他的内裤上，甚至有些精液顺着裤腿流到了他的大腿上。他肯定有很久没有发泄过了。\n")
    else:
        ui.typewriter("他的精液喷溅在床上、你的手上、身上，你有点狼狈地用衣服把自己擦干净。量有点多，他肯定有很久没有发泄过了。\n")
    time.sleep(1)
    ui.typewriter("过了许久，他才慢慢恢复了平静，脸上的红晕久久没有散去。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“我爱你。”",0.1,"bold cyan",line_break=False)
    ui.typewriter("他凑到你的耳边轻轻对你说，然后在你脸上亲了一下。你回吻了他，他的皮肤还是滚烫的。\n",0.1)
    time.sleep(0.1)
    ui.typewriter("“……你还没有到呢，”",0.2,"bold cyan",line_break=False)
    ui.typewriter("他看着你依旧硬邦邦的肉棒，伸出手去触碰它，",0.1,line_break=False)
    ui.typewriter("“我……我应该帮你。”\n",0.2,"bold cyan",line_break=False)
    time.sleep(0.1)
    ui.typewriter("（未完待续）",0.1)
    ui.typewriter("感谢你的游玩！\n\n",0.1)



